apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  labels:
    app: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/gabjea/argocd-demo:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "1.0.0"
            - name: ENABLE_PREMIUM_UI
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: ENABLE_PREMIUM_UI
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"