apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.class-demo: |
    url: https://webhook.site/3ffdeffb-5a9c-4064-b3b8-31345f27a069
    headers:
    - name: Content-Type
      value: application/json

  template.app-sync-succeeded: |
    webhook:
      class-demo:
        method: POST
        body: |
          {
            "text": "✅ GitOps Demo: Application {{.app.metadata.name}} successfully synced to commit {{.app.status.sync.revision}}!"
          }

  trigger.on-sync-succeeded: |
    - description: App synced successfully
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']